-- Oracle SQL Script to initialize the tables according to the ER Diagram

CREATE TABLE Users (
    userID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL, -- MUST store bcrypt/argon2 hash, never plain text, password is hashed bday
    firstName VARCHAR2(255) NOT NULL,
    lastName VARCHAR2(255) NOT NULL,
    nickName VARCHAR2(255),
    birthday DATE, -- Is the password, I still don't want this.
    barangay VARCHAR2(255),
    gender CHAR(1),
    dateCreated DATE DEFAULT SYSDATE,
    isDeleted NUMBER(1) DEFAULT 0 NOT NULL,
    deletedAt DATE,
    deletedBy NUMBER,
    CONSTRAINT chk_gender CHECK (gender IN ('M', 'F', 'O') OR gender IS NULL), -- M=Male, F=Female, O=Other
    CONSTRAINT chk_user_deleted CHECK (isDeleted IN (0, 1))
);

CREATE INDEX idx_users_active ON Users(isDeleted, username);

COMMENT ON TABLE Users IS 'User accounts and profile information';
COMMENT ON COLUMN Users.password IS 'Hashed password (bcrypt/argon2) - NEVER store plain text';
COMMENT ON COLUMN Users.isDeleted IS 'Soft delete flag (0=active, 1=deleted)';
COMMENT ON COLUMN Users.deletedAt IS 'Timestamp when user was soft deleted';
COMMENT ON COLUMN Users.deletedBy IS 'UserID who soft deleted this user';

CREATE TABLE Subject (
    subjectID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subjectName VARCHAR2(255) NOT NULL UNIQUE,
    description VARCHAR2(1000)
);

COMMENT ON TABLE Subject IS 'Academic subjects available in the system';
COMMENT ON COLUMN Subject.subjectName IS 'Name of the subject (e.g., Math, Science)';

CREATE TABLE Lesson (
    lessonID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subjectID NUMBER NOT NULL REFERENCES Subject(subjectID) ON DELETE CASCADE,
    lessonName VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    orderNumber NUMBER NOT NULL,
    isArchived NUMBER(1) DEFAULT 0,
    dateCreated DATE DEFAULT SYSDATE,
    CONSTRAINT chk_lesson_order CHECK (orderNumber > 0),
    CONSTRAINT chk_lesson_archived CHECK (isArchived IN (0, 1)),
    UNIQUE(subjectID, lessonName)
);

CREATE INDEX idx_lesson_subject ON Lesson(subjectID);
CREATE INDEX idx_lesson_archived ON Lesson(isArchived);

COMMENT ON TABLE Lesson IS 'Lessons organize content within subjects';
COMMENT ON COLUMN Lesson.orderNumber IS 'Display order within subject';
COMMENT ON COLUMN Lesson.isArchived IS 'Soft delete flag (0=active, 1=archived)';

CREATE TABLE Grade (
    gradeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subjectID NUMBER NOT NULL REFERENCES Subject(subjectID) ON DELETE CASCADE,
    gradeNumber NUMBER NOT NULL,
    gradeName VARCHAR2(255) NOT NULL,
    CONSTRAINT chk_grade_number CHECK (gradeNumber BETWEEN 1 AND 12),
    UNIQUE(subjectID, gradeNumber)
);

CREATE INDEX idx_grade_subject ON Grade(subjectID);

COMMENT ON TABLE Grade IS 'Grade levels within subjects';
COMMENT ON COLUMN Grade.gradeNumber IS 'Numeric grade level (1-12)';

CREATE TABLE Difficulty (
    difficultyID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficultyName VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000)
);

COMMENT ON TABLE Difficulty IS 'Difficulty levels for questions and levels';
COMMENT ON COLUMN Difficulty.difficultyName IS 'Name of difficulty (e.g., Easy, Medium, Hard)';

CREATE TABLE Level_Table (  -- "Level" is often a reserved keyword in Oracle
    levelID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gradeID NUMBER NOT NULL REFERENCES Grade(gradeID) ON DELETE CASCADE,
    difficultyID NUMBER NOT NULL REFERENCES Difficulty(difficultyID) ON DELETE RESTRICT,
    levelNumber NUMBER NOT NULL,
    levelName VARCHAR2(255) NOT NULL,
    maxScore NUMBER NOT NULL,
    passingScore NUMBER NOT NULL,
    CONSTRAINT chk_level_scores CHECK (passingScore <= maxScore AND passingScore > 0 AND maxScore > 0),
    CONSTRAINT chk_level_number CHECK (levelNumber > 0)
);

CREATE INDEX idx_level_grade ON Level_Table(gradeID);
CREATE INDEX idx_level_difficulty ON Level_Table(difficultyID);

COMMENT ON TABLE Level_Table IS 'Individual levels within grades and difficulties';
COMMENT ON COLUMN Level_Table.maxScore IS 'Maximum achievable score for this level';
COMMENT ON COLUMN Level_Table.passingScore IS 'Minimum score required to pass';

CREATE TABLE QuestionType (
    questionTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typeName VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000)
);

COMMENT ON TABLE QuestionType IS 'Types of questions (e.g., Multiple Choice, True/False, Fill-in-blank)';
COMMENT ON COLUMN QuestionType.typeName IS 'Question type identifier';

CREATE TABLE Question (
    questionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    levelID NUMBER NOT NULL REFERENCES Level_Table(levelID) ON DELETE CASCADE,
    questionTypeID NUMBER NOT NULL REFERENCES QuestionType(questionTypeID) ON DELETE RESTRICT,
    questionText VARCHAR2(4000) NOT NULL,
    questionImageURL VARCHAR2(1000),
    correctAnswer VARCHAR2(4000), -- Only for non-multiple-choice (fill-in-blank, short answer, etc)
    points NUMBER NOT NULL,
    orderNumber NUMBER NOT NULL,
    isDeleted NUMBER(1) DEFAULT 0 NOT NULL,
    deletedAt DATE,
    deletedBy NUMBER,
    dateModified DATE DEFAULT SYSDATE,
    CONSTRAINT chk_question_points CHECK (points > 0),
    CONSTRAINT chk_question_order CHECK (orderNumber > 0),
    CONSTRAINT chk_question_deleted CHECK (isDeleted IN (0, 1))
);

CREATE INDEX idx_question_level ON Question(levelID);
CREATE INDEX idx_question_type ON Question(questionTypeID);
CREATE INDEX idx_question_active ON Question(isDeleted, levelID);

COMMENT ON TABLE Question IS 'Questions for each level';
COMMENT ON COLUMN Question.points IS 'Points awarded for correct answer';
COMMENT ON COLUMN Question.orderNumber IS 'Display order within the level';
COMMENT ON COLUMN Question.dateModified IS 'Timestamp of last modification';
COMMENT ON COLUMN Question.correctAnswer IS 'Only used for non-multiple-choice questions (fill-in-blank, short answer). For multiple choice, use Answer_Choice.isCorrect instead';
COMMENT ON COLUMN Question.isDeleted IS 'Soft delete flag (0=active, 1=deleted)';
COMMENT ON COLUMN Question.deletedAt IS 'Timestamp when question was soft deleted';
COMMENT ON COLUMN Question.deletedBy IS 'UserID who soft deleted this question';

CREATE TABLE Answer_Choice (
    choiceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionID NUMBER NOT NULL REFERENCES Question(questionID) ON DELETE CASCADE,
    choiceText VARCHAR2(4000) NOT NULL,
    isCorrect NUMBER(1) NOT NULL,
    orderNumber NUMBER NOT NULL,
    isDeleted NUMBER(1) DEFAULT 0 NOT NULL,
    deletedAt DATE,
    deletedBy NUMBER,
    dateModified DATE DEFAULT SYSDATE,
    CONSTRAINT chk_answer_iscorrect CHECK (isCorrect IN (0, 1)),
    CONSTRAINT chk_answer_order CHECK (orderNumber > 0),
    CONSTRAINT chk_answer_deleted CHECK (isDeleted IN (0, 1)),
    UNIQUE(questionID, orderNumber)
);

CREATE INDEX idx_answer_question ON Answer_Choice(questionID);
CREATE INDEX idx_answer_correct ON Answer_Choice(isCorrect);
CREATE INDEX idx_answer_active ON Answer_Choice(isDeleted, questionID);

COMMENT ON TABLE Answer_Choice IS 'Multiple choice options for questions';
COMMENT ON COLUMN Answer_Choice.isCorrect IS 'Flag indicating if this is the correct answer (0=false, 1=true). For multiple choice, THIS is the source of truth, not Question.correctAnswer';
COMMENT ON COLUMN Answer_Choice.isDeleted IS 'Soft delete flag (0=active, 1=deleted)';
COMMENT ON COLUMN Answer_Choice.deletedAt IS 'Timestamp when choice was soft deleted';
COMMENT ON COLUMN Answer_Choice.deletedBy IS 'UserID who soft deleted this choice';

CREATE TABLE User_Progress (
    progressID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID NUMBER NOT NULL REFERENCES Users(userID) ON DELETE CASCADE,
    levelID NUMBER NOT NULL REFERENCES Level_Table(levelID) ON DELETE CASCADE,
    score NUMBER DEFAULT 0,
    completionStatus VARCHAR2(100),
    timeSpent NUMBER,
    dateCompleted DATE,
    attemptsCount NUMBER DEFAULT 0,
    CONSTRAINT chk_progress_score CHECK (score >= 0),
    CONSTRAINT chk_progress_time CHECK (timeSpent >= 0),
    CONSTRAINT chk_progress_attempts CHECK (attemptsCount >= 0),
    CONSTRAINT chk_progress_status CHECK (completionStatus IN ('In Progress', 'Completed', 'Failed') OR completionStatus IS NULL)
);

CREATE INDEX idx_progress_user ON User_Progress(userID);
CREATE INDEX idx_progress_level ON User_Progress(levelID);
CREATE INDEX idx_progress_user_level ON User_Progress(userID, levelID);

COMMENT ON TABLE User_Progress IS 'Tracks user progress through levels';
COMMENT ON COLUMN User_Progress.timeSpent IS 'Time spent in seconds';
COMMENT ON COLUMN User_Progress.completionStatus IS 'Current status of level attempt';

CREATE TABLE User_answer (
    userAnswerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID NUMBER NOT NULL REFERENCES Users(userID) ON DELETE CASCADE,
    questionID NUMBER NOT NULL REFERENCES Question(questionID) ON DELETE CASCADE,
    progressID NUMBER NOT NULL REFERENCES User_Progress(progressID) ON DELETE CASCADE,
    submittedAnswer VARCHAR2(4000),
    isCorrect NUMBER(1) NOT NULL,
    pointsEarned NUMBER NOT NULL,
    timeSpent NUMBER,
    dateAnswered DATE DEFAULT SYSDATE,
    CONSTRAINT chk_useranswer_iscorrect CHECK (isCorrect IN (0, 1)),
    CONSTRAINT chk_useranswer_points CHECK (pointsEarned >= 0),
    CONSTRAINT chk_useranswer_time CHECK (timeSpent >= 0)
);

CREATE INDEX idx_useranswer_user ON User_answer(userID);
CREATE INDEX idx_useranswer_question ON User_answer(questionID);
CREATE INDEX idx_useranswer_progress ON User_answer(progressID);

COMMENT ON TABLE User_answer IS 'Individual answers submitted by users';
COMMENT ON COLUMN User_answer.isCorrect IS 'Whether the answer was correct (0=false, 1=true)';
COMMENT ON COLUMN User_answer.pointsEarned IS 'Points awarded for this answer';

CREATE TABLE Achievement (
    achievementID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID NUMBER NOT NULL UNIQUE REFERENCES Users(userID) ON DELETE CASCADE,
    totalTimePlayed NUMBER DEFAULT 0,
    bronzeTokensEarned NUMBER DEFAULT 0,
    silverTokensEarned NUMBER DEFAULT 0,
    goldTokensEarned NUMBER DEFAULT 0,
    totalLevelsCompleted NUMBER DEFAULT 0,
    totalQuestionsAnswered NUMBER DEFAULT 0,
    totalCorrectAnswers NUMBER DEFAULT 0,
    lastUpdated DATE DEFAULT SYSDATE,
    CONSTRAINT chk_achievement_time CHECK (totalTimePlayed >= 0),
    CONSTRAINT chk_achievement_bronze CHECK (bronzeTokensEarned >= 0),
    CONSTRAINT chk_achievement_silver CHECK (silverTokensEarned >= 0),
    CONSTRAINT chk_achievement_gold CHECK (goldTokensEarned >= 0),
    CONSTRAINT chk_achievement_levels CHECK (totalLevelsCompleted >= 0),
    CONSTRAINT chk_achievement_questions CHECK (totalQuestionsAnswered >= 0),
    CONSTRAINT chk_achievement_correct CHECK (totalCorrectAnswers >= 0 AND totalCorrectAnswers <= totalQuestionsAnswered)
);

COMMENT ON TABLE Achievement IS 'Cumulative achievements and statistics for users';
COMMENT ON COLUMN Achievement.totalTimePlayed IS 'Total time played in seconds';
COMMENT ON COLUMN Achievement.totalLevelsCompleted IS 'Total number of levels completed (was totalLessonsCompleted - fixed mismatch)';
COMMENT ON COLUMN Achievement.lastUpdated IS 'Timestamp of last achievement update';

CREATE TABLE TokenType (
    tokenTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typeName VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    value NUMBER NOT NULL,
    imageURL VARCHAR2(1000),
    CONSTRAINT chk_tokentype_value CHECK (value > 0)
);

COMMENT ON TABLE TokenType IS 'Types of tokens that can be earned (Bronze, Silver, Gold)';
COMMENT ON COLUMN TokenType.value IS 'Relative value of this token type';

CREATE TABLE TokenTransaction (
    tokenTransactionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID NUMBER NOT NULL REFERENCES Users(userID) ON DELETE CASCADE,
    tokenTypeID NUMBER NOT NULL REFERENCES TokenType(tokenTypeID) ON DELETE RESTRICT,
    amount NUMBER NOT NULL,
    source VARCHAR2(255),
    referenceID NUMBER,
    dateEarned DATE DEFAULT SYSDATE,
    CONSTRAINT chk_token_amount CHECK (amount > 0)
);

CREATE INDEX idx_token_user ON TokenTransaction(userID);
CREATE INDEX idx_token_type ON TokenTransaction(tokenTypeID);
CREATE INDEX idx_token_date ON TokenTransaction(dateEarned);

COMMENT ON TABLE TokenTransaction IS 'History of token earnings by users';
COMMENT ON COLUMN TokenTransaction.source IS 'Source of token earning (e.g., level completion, achievement)';
COMMENT ON COLUMN TokenTransaction.referenceID IS 'Reference to source record (e.g., progressID, levelID)';

-- Audit Trail Table
CREATE TABLE Audit_Log (
    auditID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tableName VARCHAR2(255) NOT NULL,
    recordID NUMBER NOT NULL,
    action VARCHAR2(50) NOT NULL,
    changedBy NUMBER,
    changedAt DATE DEFAULT SYSDATE,
    oldValues CLOB,
    newValues CLOB,
    ipAddress VARCHAR2(45),
    userAgent VARCHAR2(500),
    CONSTRAINT chk_audit_action CHECK (action IN ('INSERT', 'UPDATE', 'HARD_DELETE', 'SOFT_DELETE', 'RESTORE'))
);

CREATE INDEX idx_audit_table ON Audit_Log(tableName, recordID);
CREATE INDEX idx_audit_date ON Audit_Log(changedAt);
CREATE INDEX idx_audit_user ON Audit_Log(changedBy);

COMMENT ON TABLE Audit_Log IS 'Comprehensive audit trail for all critical table changes';
COMMENT ON COLUMN Audit_Log.tableName IS 'Name of the table that was modified';
COMMENT ON COLUMN Audit_Log.recordID IS 'Primary key of the modified record';
COMMENT ON COLUMN Audit_Log.action IS 'Type of action performed';
COMMENT ON COLUMN Audit_Log.changedBy IS 'UserID who made the change';
COMMENT ON COLUMN Audit_Log.oldValues IS 'JSON of old values before change';
COMMENT ON COLUMN Audit_Log.newValues IS 'JSON of new values after change';

-- Audit Triggers for critical tables
CREATE OR REPLACE TRIGGER trg_users_audit
BEFORE UPDATE ON Users
FOR EACH ROW
BEGIN
    :NEW.dateCreated := :OLD.dateCreated; -- Prevent modification of creation date
END;
/

CREATE OR REPLACE TRIGGER trg_achievement_timestamp
BEFORE UPDATE ON Achievement
FOR EACH ROW
BEGIN
    :NEW.lastUpdated := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_question_timestamp
BEFORE UPDATE ON Question
FOR EACH ROW
BEGIN
    :NEW.dateModified := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_answer_choice_timestamp
BEFORE UPDATE ON Answer_Choice
FOR EACH ROW
BEGIN
    :NEW.dateModified := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_prevent_score_decrease
BEFORE UPDATE ON User_Progress
FOR EACH ROW
BEGIN
    IF :NEW.score < :OLD.score THEN
        RAISE_APPLICATION_ERROR(-20001, 'Score cannot be decreased');
    END IF;
END;
/

-- Soft Delete Triggers
CREATE OR REPLACE TRIGGER trg_users_soft_delete
BEFORE UPDATE ON Users
FOR EACH ROW
WHEN (NEW.isDeleted = 1 AND OLD.isDeleted = 0)
BEGIN
    :NEW.deletedAt := SYSDATE;
    -- Insert audit log
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Users', :OLD.userID, 'SOFT_DELETE', :NEW.deletedBy, 
            'username: ' || :OLD.username, 
            'DELETED');
END;
/

CREATE OR REPLACE TRIGGER trg_question_soft_delete
BEFORE UPDATE ON Question
FOR EACH ROW
WHEN (NEW.isDeleted = 1 AND OLD.isDeleted = 0)
BEGIN
    :NEW.deletedAt := SYSDATE;
    -- Insert audit log
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Question', :OLD.questionID, 'SOFT_DELETE', :NEW.deletedBy,
            'questionText: ' || SUBSTR(:OLD.questionText, 1, 100),
            'DELETED');
END;
/

CREATE OR REPLACE TRIGGER trg_answer_soft_delete
BEFORE UPDATE ON Answer_Choice
FOR EACH ROW
WHEN (NEW.isDeleted = 1 AND OLD.isDeleted = 0)
BEGIN
    :NEW.deletedAt := SYSDATE;
    -- Insert audit log
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Answer_Choice', :OLD.choiceID, 'SOFT_DELETE', :NEW.deletedBy,
            'choiceText: ' || SUBSTR(:OLD.choiceText, 1, 100),
            'DELETED');
END;
/

-- Restore Triggers (when isDeleted changes from 1 to 0)
CREATE OR REPLACE TRIGGER trg_users_restore
BEFORE UPDATE ON Users
FOR EACH ROW
WHEN (NEW.isDeleted = 0 AND OLD.isDeleted = 1)
BEGIN
    :NEW.deletedAt := NULL;
    :NEW.deletedBy := NULL;
    -- Insert audit log
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Users', :OLD.userID, 'RESTORE', :NEW.deletedBy,
            'DELETED',
            'username: ' || :NEW.username);
END;
/

-- Comprehensive Audit Logging Triggers for INSERT operations
CREATE OR REPLACE TRIGGER trg_users_insert_audit
AFTER INSERT ON Users
FOR EACH ROW
BEGIN
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Users', :NEW.userID, 'INSERT', :NEW.userID,
            NULL,
            'username: ' || :NEW.username || ', firstName: ' || :NEW.firstName || ', lastName: ' || :NEW.lastName);
END;
/

CREATE OR REPLACE TRIGGER trg_question_insert_audit
AFTER INSERT ON Question
FOR EACH ROW
BEGIN
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Question', :NEW.questionID, 'INSERT', NULL,
            NULL,
            'levelID: ' || :NEW.levelID || ', points: ' || :NEW.points || ', text: ' || SUBSTR(:NEW.questionText, 1, 50));
END;
/

CREATE OR REPLACE TRIGGER trg_answer_insert_audit
AFTER INSERT ON Answer_Choice
FOR EACH ROW
BEGIN
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Answer_Choice', :NEW.choiceID, 'INSERT', NULL,
            NULL,
            'questionID: ' || :NEW.questionID || ', isCorrect: ' || :NEW.isCorrect || ', text: ' || SUBSTR(:NEW.choiceText, 1, 50));
END;
/

-- Comprehensive Audit Logging Triggers for UPDATE operations (non-soft-delete updates)
CREATE OR REPLACE TRIGGER trg_users_update_audit
AFTER UPDATE ON Users
FOR EACH ROW
WHEN (OLD.isDeleted = NEW.isDeleted OR (OLD.isDeleted = 0 AND NEW.isDeleted = 0))
BEGIN
    -- Only log non-soft-delete updates
    IF (OLD.isDeleted = NEW.isDeleted) THEN
        INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
        VALUES ('Users', :NEW.userID, 'UPDATE', :NEW.userID,
                'firstName: ' || :OLD.firstName || ', lastName: ' || :OLD.lastName || ', gender: ' || :OLD.gender,
                'firstName: ' || :NEW.firstName || ', lastName: ' || :NEW.lastName || ', gender: ' || :NEW.gender);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trg_question_update_audit
AFTER UPDATE ON Question
FOR EACH ROW
WHEN (OLD.isDeleted = NEW.isDeleted)
BEGIN
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Question', :NEW.questionID, 'UPDATE', NULL,
            'points: ' || :OLD.points || ', text: ' || SUBSTR(:OLD.questionText, 1, 50),
            'points: ' || :NEW.points || ', text: ' || SUBSTR(:NEW.questionText, 1, 50));
END;
/

CREATE OR REPLACE TRIGGER trg_answer_update_audit
AFTER UPDATE ON Answer_Choice
FOR EACH ROW
WHEN (OLD.isDeleted = NEW.isDeleted)
BEGIN
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Answer_Choice', :NEW.choiceID, 'UPDATE', NULL,
            'isCorrect: ' || :OLD.isCorrect || ', text: ' || SUBSTR(:OLD.choiceText, 1, 50),
            'isCorrect: ' || :NEW.isCorrect || ', text: ' || SUBSTR(:NEW.choiceText, 1, 50));
END;
/

-- Hard DELETE Triggers (permanent deletion of records)
CREATE OR REPLACE TRIGGER trg_users_hard_delete
BEFORE DELETE ON Users
FOR EACH ROW
BEGIN
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Users', :OLD.userID, 'HARD_DELETE', :OLD.deletedBy,
            'username: ' || :OLD.username || ', firstName: ' || :OLD.firstName,
            'PERMANENTLY_DELETED');
END;
/

CREATE OR REPLACE TRIGGER trg_question_hard_delete
BEFORE DELETE ON Question
FOR EACH ROW
BEGIN
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Question', :OLD.questionID, 'HARD_DELETE', NULL,
            'levelID: ' || :OLD.levelID || ', points: ' || :OLD.points,
            'PERMANENTLY_DELETED');
END;
/

CREATE OR REPLACE TRIGGER trg_answer_hard_delete
BEFORE DELETE ON Answer_Choice
FOR EACH ROW
BEGIN
    INSERT INTO Audit_Log (tableName, recordID, action, changedBy, oldValues, newValues)
    VALUES ('Answer_Choice', :OLD.choiceID, 'HARD_DELETE', NULL,
            'questionID: ' || :OLD.questionID || ', isCorrect: ' || :OLD.isCorrect,
            'PERMANENTLY_DELETED');
END;
/
