-- Oracle SQL Script to initialize the tables according to the ER Diagram

CREATE TABLE Theme (
    themeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    themeName VARCHAR2(255) NOT NULL,
    themeDescription VARCHAR2(1000),
    imageURL VARCHAR2(1000)
);

CREATE TABLE Users (
    userID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    firstName VARCHAR2(255) NOT NULL,
    lastName VARCHAR2(255) NOT NULL,
    nickName VARCHAR2(255),
    birthday DATE,
    barangay VARCHAR2(255),
    gender VARCHAR2(50),
    themeID NUMBER REFERENCES Theme(themeID),
    dateCreated DATE DEFAULT SYSDATE
);

CREATE TABLE Subject (
    subjectID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subjectName VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000)
);

CREATE TABLE Grade (
    gradeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subjectID NUMBER NOT NULL REFERENCES Subject(subjectID),
    gradeNumber NUMBER NOT NULL,
    gradeName VARCHAR2(255) NOT NULL
);

CREATE TABLE Difficulty (
    difficultyID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficultyName VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000)
);

CREATE TABLE Level_Table (  -- "Level" is often a reserved keyword in Oracle
    levelID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gradeID NUMBER NOT NULL REFERENCES Grade(gradeID),
    difficultyID NUMBER NOT NULL REFERENCES Difficulty(difficultyID),
    levelNumber NUMBER NOT NULL,
    levelName VARCHAR2(255) NOT NULL,
    maxScore NUMBER NOT NULL,
    passingScore NUMBER NOT NULL
);

CREATE TABLE QuestionType (
    questionTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typeName VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000)
);

CREATE TABLE Question (
    questionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    levelID NUMBER NOT NULL REFERENCES Level_Table(levelID),
    questionTypeID NUMBER NOT NULL REFERENCES QuestionType(questionTypeID),
    questionText VARCHAR2(4000) NOT NULL,
    questionImageURL VARCHAR2(1000),
    correctAnswer VARCHAR2(4000),
    points NUMBER NOT NULL,
    orderNumber NUMBER NOT NULL
);

CREATE TABLE Answer_Choice (
    choiceID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionID NUMBER NOT NULL REFERENCES Question(questionID),
    choiceText VARCHAR2(4000) NOT NULL,
    isCorrect NUMBER(1) NOT NULL, -- 0 or 1 for boolean
    orderNumber NUMBER NOT NULL
);

CREATE TABLE User_Progress (
    progressID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID NUMBER NOT NULL REFERENCES Users(userID),
    levelID NUMBER NOT NULL REFERENCES Level_Table(levelID),
    score NUMBER DEFAULT 0,
    completionStatus VARCHAR2(100),
    timeSpent NUMBER,
    dateCompleted DATE,
    attemptsCount NUMBER DEFAULT 0
);

CREATE TABLE User_answer (
    userAnswerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID NUMBER NOT NULL REFERENCES Users(userID),
    questionID NUMBER NOT NULL REFERENCES Question(questionID),
    progressID NUMBER NOT NULL REFERENCES User_Progress(progressID),
    submittedAnswer VARCHAR2(4000),
    isCorrect NUMBER(1) NOT NULL,
    pointsEarned NUMBER NOT NULL,
    timeSpent NUMBER,
    dateAnswered DATE DEFAULT SYSDATE
);

CREATE TABLE Achievement (
    userID NUMBER PRIMARY KEY REFERENCES Users(userID),
    totalTimePlayed NUMBER DEFAULT 0,
    bronzeTokensEarned NUMBER DEFAULT 0,
    silverTokensEarned NUMBER DEFAULT 0,
    goldTokensEarned NUMBER DEFAULT 0,
    totalLessonsCompleted NUMBER DEFAULT 0,
    totalLevelsCompleted NUMBER DEFAULT 0,
    totalQuestionsAnswered NUMBER DEFAULT 0,
    totalCorrectAnswers NUMBER DEFAULT 0,
    lastUpdated DATE DEFAULT SYSDATE
);

CREATE TABLE TokenType (
    tokenTypeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    typeName VARCHAR2(255) NOT NULL,
    description VARCHAR2(1000),
    value NUMBER NOT NULL,
    imageURL VARCHAR2(1000)
);

CREATE TABLE TokenTransaction (
    tokenTransactionID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID NUMBER NOT NULL REFERENCES Users(userID),
    tokenTypeID NUMBER NOT NULL REFERENCES TokenType(tokenTypeID),
    amount NUMBER NOT NULL,
    source VARCHAR2(255),
    referenceID NUMBER,
    dateEarned DATE DEFAULT SYSDATE
);
